using System.Diagnostics;

namespace ShadowingEnglish.Api.Modules.Media;

public interface IShadowingMediaStore
{
    bool IsConfigured { get; }
    Task WriteAsync(string key, Stream source, CancellationToken cancellation);
    Task<bool> MatchesAsync(string key, Stream source, CancellationToken cancellation);
    Task<bool> ExistsAsync(string key, CancellationToken cancellation);
    Task<ShadowingMediaRead?> OpenAsync(string key, CancellationToken cancellation);
    Task DeleteAsync(string key, CancellationToken cancellation);
}

public sealed record ShadowingMediaRead(Stream Content, long Length,
    DateTimeOffset LastModified, string ETag);

public sealed class MediaStorageUnavailableException : IOException
{
    public MediaStorageUnavailableException() : base("media_storage_unavailable") { }
}

// Asset keys are generated by the API, never user paths, URLs or original filenames.
public static class ShadowingMediaKeys
{
    public static bool IsValid(string key) => key.Length <= 100 &&
        System.Text.RegularExpressions.Regex.IsMatch(key, "^[a-z0-9-]+\\.wav$",
            System.Text.RegularExpressions.RegexOptions.CultureInvariant);
    public static void Validate(string key)
    {
        if (!IsValid(key)) throw new ArgumentException("invalid_media_key");
    }
}

public abstract class DiagnosticMediaStore(ILogger logger, string provider) : IShadowingMediaStore
{
    public abstract bool IsConfigured { get; }
    public abstract Task WriteAsync(string key, Stream source, CancellationToken cancellation);
    public abstract Task<bool> MatchesAsync(string key, Stream source, CancellationToken cancellation);
    public abstract Task<bool> ExistsAsync(string key, CancellationToken cancellation);
    public abstract Task<ShadowingMediaRead?> OpenAsync(string key, CancellationToken cancellation);
    public abstract Task DeleteAsync(string key, CancellationToken cancellation);

    protected async Task<T> Track<T>(string operation, string key, Func<Task<T>> action,
        long? bytes = null)
    {
        ShadowingMediaKeys.Validate(key);
        var started = Stopwatch.GetTimestamp();
        logger.LogInformation("Media.{Operation}.Start Provider={Provider} AssetKey={AssetKey} Bytes={Bytes}",
            operation, provider, key, bytes);
        try
        {
            var result = await action();
            logger.LogInformation("Media.{Operation}.Success Provider={Provider} AssetKey={AssetKey} Bytes={Bytes} DurationMs={DurationMs}",
                operation, provider, key, result is ShadowingMediaRead read ? read.Length : bytes,
                Stopwatch.GetElapsedTime(started).TotalMilliseconds);
            return result;
        }
        catch (OperationCanceledException)
        {
            logger.LogInformation("Media.{Operation}.Cancelled Provider={Provider} AssetKey={AssetKey} DurationMs={DurationMs}",
                operation, provider, key, Stopwatch.GetElapsedTime(started).TotalMilliseconds);
            throw;
        }
        catch (Exception error)
        {
            // SDK exceptions can contain URLs/headers. Log safe codes, never the exception body.
            logger.LogWarning("Media.{Operation}.Failed Provider={Provider} AssetKey={AssetKey} ErrorType={ErrorType} DurationMs={DurationMs}",
                operation, provider, key, error.GetType().Name, Stopwatch.GetElapsedTime(started).TotalMilliseconds);
            throw new MediaStorageUnavailableException();
        }
    }
}

public sealed class DisabledShadowingMediaStore : IShadowingMediaStore
{
    public bool IsConfigured => false;
    public Task WriteAsync(string key, Stream source, CancellationToken cancellation) => throw new MediaStorageUnavailableException();
    public Task<bool> MatchesAsync(string key, Stream source, CancellationToken cancellation) => throw new MediaStorageUnavailableException();
    public Task<bool> ExistsAsync(string key, CancellationToken cancellation) => throw new MediaStorageUnavailableException();
    public Task<ShadowingMediaRead?> OpenAsync(string key, CancellationToken cancellation) => throw new MediaStorageUnavailableException();
    public Task DeleteAsync(string key, CancellationToken cancellation) => throw new MediaStorageUnavailableException();
}
